-- Forte Savings JWT Authentication Fix
-- This script ensures proper JWT secret initialization

-- Make sure system_settings table exists
CREATE TABLE IF NOT EXISTS system_settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    setting_key VARCHAR(100) UNIQUE NOT NULL,
    setting_value TEXT,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Clear any existing empty jwt_secret
DELETE FROM system_settings WHERE setting_key = 'jwt_secret' AND (setting_value IS NULL OR setting_value = '');

-- Add proper JWT secret if not exists
INSERT IGNORE INTO system_settings (setting_key, setting_value, description) 
VALUES ('jwt_secret', NULL, 'JWT Secret Key - Will be auto-generated by JWTManager');

-- Add other required system settings if not exist
INSERT IGNORE INTO system_settings (setting_key, setting_value, description) VALUES
('app_name', 'Forte Savings', 'Application name'),
('app_version', '1.0.1', 'Application version'),
('default_currency', 'TRY', 'Default currency'),
('date_format', 'Y-m-d', 'Default date format'),
('email_domain', '@fortetourism.com', 'Allowed email domain');

-- Show current system settings
SELECT * FROM system_settings ORDER BY setting_key;